/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RankingRouteImport } from "./routes/ranking";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as BattleRouteImport } from "./routes/battle";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiTrpcSplatRouteImport } from "./routes/api/trpc/$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const RankingRoute = RankingRouteImport.update({
  id: "/ranking",
  path: "/ranking",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const BattleRoute = BattleRouteImport.update({
  id: "/battle",
  path: "/battle",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: "/api/trpc/$",
  path: "/api/trpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/battle": typeof BattleRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/ranking": typeof RankingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/battle": typeof BattleRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/ranking": typeof RankingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/battle": typeof BattleRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/ranking": typeof RankingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/trpc/$": typeof ApiTrpcSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/battle"
    | "/dashboard"
    | "/login"
    | "/ranking"
    | "/api/auth/$"
    | "/api/trpc/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/battle"
    | "/dashboard"
    | "/login"
    | "/ranking"
    | "/api/auth/$"
    | "/api/trpc/$";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/battle"
    | "/dashboard"
    | "/login"
    | "/ranking"
    | "/api/auth/$"
    | "/api/trpc/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  BattleRoute: typeof BattleRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  RankingRoute: typeof RankingRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/ranking": {
      id: "/ranking";
      path: "/ranking";
      fullPath: "/ranking";
      preLoaderRoute: typeof RankingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/battle": {
      id: "/battle";
      path: "/battle";
      fullPath: "/battle";
      preLoaderRoute: typeof BattleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/trpc/$": {
      id: "/api/trpc/$";
      path: "/api/trpc/$";
      fullPath: "/api/trpc/$";
      preLoaderRoute: typeof ApiTrpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BattleRoute: BattleRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
